stages:
  - test
  - build
  - deploy

image: node:lts-alpine

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn test
  artifacts:
    paths:
      - coverage

build:
  stage: build
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - storybook-static

pages:
  stage: deploy
  script:
    - yarn build-storybook
    - mv storybook-static public
  artifacts:
    paths:
      - public
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
