name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tags:'
        required: true
        type: string
      environment:
        description: 'Environment:'
        type: choice
        options:
          - staging
          - production
        required: true

jobs:
  daploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: "Daploy tag:"
        run: echo  "${{ github.event.inputs.tag }}"
      - name: "Daploy environment:"
        run: echo  "${{ github.event.inputs.environment }}"
