name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: borales/actions-yarn@v3.0.2
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.2
        with:
          cmd: test
      - uses: borales/actions-yarn@v3.0.2
        with:
          cmd: test
